28/10/22 (12:33:43) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
01/11/22 (01:51:43) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
02/11/22 (00:18:10) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
02/11/22 (00:22:30) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
02/11/22 (00:24:17) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
04/11/22 (00:57:49) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
04/11/22 (02:37:18) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
04/11/22 (02:38:07) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
04/11/22 (02:42:52) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
04/11/22 (02:44:17) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
04/11/22 (02:46:07) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
05/11/22 (00:52:15) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
05/11/22 (12:55:42) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
05/11/22 (22:00:14) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
05/11/22 (22:35:13) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
14/11/22 (22:59:47) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
14/11/22 (22:59:55) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
14/11/22 (23:04:54) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
17/11/22 (02:03:01) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
22/11/22 (20:53:34) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
24/11/22 (12:15:29) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
24/11/22 (12:28:57) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
24/11/22 (23:48:26) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
28/11/22 (22:29:37) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
28/11/22 (22:36:18) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 954, in _get_key
    with Raw(sys.stdin):
  File "/usr/bin/bpytop", line 798, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
02/12/22 (00:47:16) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
02/12/22 (11:37:43) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
02/12/22 (11:41:12) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 954, in _get_key
    with Raw(sys.stdin):
  File "/usr/bin/bpytop", line 798, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
10/12/22 (11:14:58) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
12/12/22 (01:46:46) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
18/12/22 (00:10:13) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
18/12/22 (01:30:10) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 954, in _get_key
    with Raw(sys.stdin):
  File "/usr/bin/bpytop", line 798, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
21/12/22 (10:01:02) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
