28/10/22 (12:33:43) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
01/11/22 (01:51:43) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
02/11/22 (00:18:10) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
02/11/22 (00:22:30) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
02/11/22 (00:24:17) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
04/11/22 (00:57:49) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
04/11/22 (02:37:18) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
04/11/22 (02:38:07) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
04/11/22 (02:42:52) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
04/11/22 (02:44:17) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
04/11/22 (02:46:07) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
05/11/22 (00:52:15) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
05/11/22 (12:55:42) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
05/11/22 (22:00:14) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
05/11/22 (22:35:13) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
14/11/22 (22:59:47) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
14/11/22 (22:59:55) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
14/11/22 (23:04:54) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
17/11/22 (02:03:01) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
